all:
	$(CC) -g linked-list.c -o linked-list
	$(CC) -g sorting.c -o sorting
	$(CC) -g -lm geometric.c -o geometric
	$(CC) -g recursive.c -o recursive

clean:
	$(RM) linked-list sorting geometric recursive *.o
